export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE';

export const PROJECT_GET_REQUEST = 'PROJECT_GET_REQUEST';
export const PROJECT_GET_SUCCESS = 'PROJECT_GET_SUCCESS';
export const PROJECT_GET_FAILURE = 'PROJECT_GET_FAILURE';

export const PROJECT_GET_ALL_REQUEST = 'PROJECT_GET_ALL_REQUEST';
export const PROJECT_GET_ALL_SUCCESS = 'PROJECT_GET_ALL_SUCCESS';
export const PROJECT_GET_ALL_FAILURE = 'PROJECT_GET_ALL_FAILURE';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

// Track Action Types
export const TRACK_CREATE_REQUEST = 'TRACK_CREATE_REQUEST';
export const TRACK_CREATE_SUCCESS = 'TRACK_CREATE_SUCCESS';
export const TRACK_CREATE_FAILURE = 'TRACK_CREATE_FAILURE';

export const TRACK_GET_ALL_REQUEST = 'TRACK_GET_ALL_REQUEST';
export const TRACK_GET_ALL_SUCCESS = 'TRACK_GET_ALL_SUCCESS';
export const TRACK_GET_ALL_FAILURE = 'TRACK_GET_ALL_FAILURE';

export const TRACK_GET_REQUEST = 'TRACK_GET_REQUEST';
export const TRACK_GET_SUCCESS = 'TRACK_GET_SUCCESS';
export const TRACK_GET_FAILURE = 'TRACK_GET_FAILURE';

export const TRACK_UPDATE_REQUEST = 'TRACK_UPDATE_REQUEST';
export const TRACK_UPDATE_SUCCESS = 'TRACK_UPDATE_SUCCESS';
export const TRACK_UPDATE_FAILURE = 'TRACK_UPDATE_FAILURE';

export const TRACK_DELETE_REQUEST = 'TRACK_DELETE_REQUEST';
export const TRACK_DELETE_SUCCESS = 'TRACK_DELETE_SUCCESS';
export const TRACK_DELETE_FAILURE = 'TRACK_DELETE_FAILURE';

// Comment Action Types
export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAILURE = 'COMMENT_CREATE_FAILURE';

export const COMMENT_GET_ALL_REQUEST = 'COMMENT_GET_ALL_REQUEST';
export const COMMENT_GET_ALL_SUCCESS = 'COMMENT_GET_ALL_SUCCESS';
export const COMMENT_GET_ALL_FAILURE = 'COMMENT_GET_ALL_FAILURE';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';