export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE';

export const PROJECT_GET_REQUEST = 'PROJECT_GET_REQUEST';
export const PROJECT_GET_SUCCESS = 'PROJECT_GET_SUCCESS';
export const PROJECT_GET_FAILURE = 'PROJECT_GET_FAILURE';

export const PROJECT_GET_ALL_REQUEST = 'PROJECT_GET_ALL_REQUEST';
export const PROJECT_GET_ALL_SUCCESS = 'PROJECT_GET_ALL_SUCCESS';
export const PROJECT_GET_ALL_FAILURE = 'PROJECT_GET_ALL_FAILURE';

export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

// Track Action Types
export const TRACK_CREATE_REQUEST = 'TRACK_CREATE_REQUEST';
export const TRACK_CREATE_SUCCESS = 'TRACK_CREATE_SUCCESS';
export const TRACK_CREATE_FAILURE = 'TRACK_CREATE_FAILURE';

export const TRACK_GET_ALL_REQUEST = 'TRACK_GET_ALL_REQUEST';
export const TRACK_GET_ALL_SUCCESS = 'TRACK_GET_ALL_SUCCESS';
export const TRACK_GET_ALL_FAILURE = 'TRACK_GET_ALL_FAILURE';

export const TRACK_GET_REQUEST = 'TRACK_GET_REQUEST';
export const TRACK_GET_SUCCESS = 'TRACK_GET_SUCCESS';
export const TRACK_GET_FAILURE = 'TRACK_GET_FAILURE';

export const TRACK_UPDATE_REQUEST = 'TRACK_UPDATE_REQUEST';
export const TRACK_UPDATE_SUCCESS = 'TRACK_UPDATE_SUCCESS';
export const TRACK_UPDATE_FAILURE = 'TRACK_UPDATE_FAILURE';

export const TRACK_DELETE_REQUEST = 'TRACK_DELETE_REQUEST';
export const TRACK_DELETE_SUCCESS = 'TRACK_DELETE_SUCCESS';
export const TRACK_DELETE_FAILURE = 'TRACK_DELETE_FAILURE';

// Comment Action Types
export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAILURE = 'COMMENT_CREATE_FAILURE';

export const COMMENT_GET_ALL_REQUEST = 'COMMENT_GET_ALL_REQUEST';
export const COMMENT_GET_ALL_SUCCESS = 'COMMENT_GET_ALL_SUCCESS';
export const COMMENT_GET_ALL_FAILURE = 'COMMENT_GET_ALL_FAILURE';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';

// Music Data Action Types
export const TRACK_UPDATE_MUSIC_DATA = 'TRACK_UPDATE_MUSIC_DATA';

// Version Control Action Types
export const GET_PROJECT_VERSIONS_REQUEST = 'GET_PROJECT_VERSIONS_REQUEST';
export const GET_PROJECT_VERSIONS_SUCCESS = 'GET_PROJECT_VERSIONS_SUCCESS';
export const GET_PROJECT_VERSIONS_FAILURE = 'GET_PROJECT_VERSIONS_FAILURE';

export const REVERT_PROJECT_REQUEST = 'REVERT_PROJECT_REQUEST';
export const REVERT_PROJECT_SUCCESS = 'REVERT_PROJECT_SUCCESS';
export const REVERT_PROJECT_FAILURE = 'REVERT_PROJECT_FAILURE';

// Search Action Types
export const SEARCH_PROJECTS_REQUEST = 'SEARCH_PROJECTS_REQUEST';
export const SEARCH_PROJECTS_SUCCESS = 'SEARCH_PROJECTS_SUCCESS';
export const SEARCH_PROJECTS_FAILURE = 'SEARCH_PROJECTS_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'; // To clear results

// Recommendation Action Types
export const GET_PROJECT_RECS_REQUEST = 'GET_PROJECT_RECS_REQUEST';
export const GET_PROJECT_RECS_SUCCESS = 'GET_PROJECT_RECS_SUCCESS';
export const GET_PROJECT_RECS_FAILURE = 'GET_PROJECT_RECS_FAILURE';

export const GET_USER_RECS_REQUEST = 'GET_USER_RECS_REQUEST';
export const GET_USER_RECS_SUCCESS = 'GET_USER_RECS_SUCCESS';
export const GET_USER_RECS_FAILURE = 'GET_USER_RECS_FAILURE';

// Follow Action Types
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';

// Update user profile data (following list)
export const UPDATE_USER_FOLLOWING = 'UPDATE_USER_FOLLOWING';

// Save Project Version Action Types
export const SAVE_PROJECT_VERSION_REQUEST = 'SAVE_PROJECT_VERSION_REQUEST';
export const SAVE_PROJECT_VERSION_SUCCESS = 'SAVE_PROJECT_VERSION_SUCCESS';
export const SAVE_PROJECT_VERSION_FAILURE = 'SAVE_PROJECT_VERSION_FAILURE';